[package]
name = "aglium"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "unwind"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true
panic = "unwind"

[dependencies]
glium = { version="0.27" }
stb_image = { version="0.2" }
glam = { version="0.8" }
serde = { version="1.0", features=[ "derive" ] }
serde_json = { version="1.0" }
