[package]
name = "ayude"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"
default-run = "ayude"

[profile.dev]
panic = "unwind"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true
panic = "unwind"

[dependencies]
glutin = "0"
gl = "0"
glam = "0"
image = { version="0", default-features=false, features=["png", "jpeg"] }
serde = { version="1", features=[ "derive" ] }
serde_bytes = "0"
serde_json = "1"