[package]
name = "aglium"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "unwind"

[profile.release]
panic = "unwind"

[dependencies.glium]
version = "*"

[dependencies.image]
version = "0.23"
default-features = false
features = [ "png" ]

[dependencies.cgmath]
version = "0.17"

[dependencies.gltf]
version = "*"