[package]
name = "ayude"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "unwind"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true
panic = "unwind"

[dependencies]
glfw = "0.37"
gl = "0.14"
stb_image = "0.2"
glam = "0.8"
serde = { version="1.0", features=[ "derive" ] }
serde_json = "1.0"
futures = { version="0.3", default-features=false, features=["thread-pool"] }
