[package]
name = "ayude"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"
default-run = "ayude"

[profile.dev]
panic = "unwind"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true
panic = "unwind"

[dependencies]
glutin = "0.24"
gl = "0.14"
glam = "0.8"
image = { version="0.23", default-features=false, features=["png", "jpeg"] }
serde = { version="1.0", features=[ "derive" ] }
serde_bytes = "0.11"
serde_json = "1.0"
bincode = "1.2"
blend = "0"