[package]
name = "aglium"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[dependencies.glium]
version = "*"

[dependencies.image]
version = "0.23.4"
default-features = false
features = [ "png" ]