[package]
name = "aglium"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"

[profile.dev]
panic = "unwind"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
panic = "unwind"
debug = true

[dependencies.glium]
version = "*"

[dependencies.stb_image]
version = "0.2"

[dependencies.euler]
version = "*"

[dependencies.gltf]
path = "gltf"

[dependencies.anyhow]
version = "*"