[package]
name = "ayude"
version = "1.0.0"
authors = ["Pablo Tato Ramos <pabtatoramos@gmail.com>"]
edition = "2018"
default-run = "ayude"

[profile.dev.package."*"]
opt-level = 2

[profile.release]
debug = true

[dependencies]
glutin = "0"
gl = "0"
glam = "0"
image = { version="0", default-features=false, features=["png", "jpeg"] }
gltf = { version="0.16", features=["utils"] }

msgbox = "0"